Add version flag
wojpawlik/deno2node pull request #17
Opened 2021-11-20 21:50 UTC by KnorpelSenf

Implements `--version` and `-v` for the CLI. Example output:

```bash
$ deno2node --version
deno2node 1.0.1
ts-morph 12.0.0
typescript 4.4.4
```

2021-11-20 21:59 UTC, KnorpelSenf commented
This requires the `ts-morph` version string to be updated manually whenever a the ts-morph dependency is updated.

Note also that future version released must be performed using `npm version` so that the correct version string of `deno2node` can be injected before the release.

2021-11-20 22:07 UTC, wojpawlik requested changes

2021-11-20 22:07 UTC, wojpawlik commented on package.json
> +    "version": "npm run inject-version && git add src/version.ts && git commit -m \"Update version to $npm_package_version\"",
I dislike this. `deps.deno.ts` could use `fetch` relative to `import.main.meta`.

2021-11-20 22:07 UTC, wojpawlik commented on src/deps.node.ts
> +export const tsMorphVersion = "12.2.0";
Unnecessary. `ts.version` is sufficient and easy to obtain.

2021-11-20 22:13 UTC, wojpawlik commented on src/deps.node.ts
> +export const tsMorphVersion = "12.2.0";
Alternatively, perhaps it could be read from `package*.json`

2021-11-20 22:15 UTC, wojpawlik commented on src/deps.node.ts
> +export const tsMorphVersion = "12.2.0";
And it might change across `npm install`s, since npm allows semver-minor updates by default

2021-11-20 23:30 UTC, wojpawlik requested changes

2021-11-20 23:30 UTC, wojpawlik commented on src/deps.node.ts
> +  const packageJson = require("./package.json");
Won't work, `deno2node` is ESM.

2021-11-20 23:30 UTC, wojpawlik commented on src/deps.deno.ts
> +  const path = join(thisDir, "..", "package.json");
Slight simplification:

```suggestion
  const path = join(import.meta.url, "../..", "package.json");
```

2021-11-20 23:32 UTC, KnorpelSenf commented on src/deps.node.ts
> +  const packageJson = require("./package.json");
Good point …

2021-11-20 23:47 UTC, KnorpelSenf commented on src/deps.deno.ts
> +  const path = join(thisDir, "..", "package.json");
Must use `dirname` on Deno.

2021-11-20 23:48 UTC, wojpawlik approved these changes

2021-11-20 23:48 UTC, wojpawlik commented on src/shim.node.ts
> +  const data = await readFile(localPath.substr(5), { encoding: "utf-8" });
Slighly neater with `URL`:

```suggestion
  url: URL,
  // deno-lint-ignore no-explicit-any
): Promise<{ json: () => Promise<any> }> {
  if (url.protocol !== "file:") {
    throw new Error("Can only read local files!");
  }
  const data = await readFile(url, { encoding: "utf-8" });
```

2021-11-20 23:48 UTC, wojpawlik commented on src/cli.ts
> +    const res = await fetch(file);
```suggestion
    const url = new URL("../../package.json", import.meta.url);
    const res = await fetch(url);
```

2021-11-20 23:57 UTC, KnorpelSenf commented
How would we add tests for this?

2021-11-21 16:19 UTC, KnorpelSenf commented
That was simple. Thanks!

2021-11-21 16:22 UTC, merged